"""
2026 NFL Coaching Tree Lineage, Scheme Ecosystems & Fantasy Playcaller Tendencies.
Provides comprehensive classifications of high-value systems (Shanahan / McVay / Reid trees),
pre-snap motion rates, personnel groupings (11 vs 12/21 personnel), PROE, and red zone tendencies.
"""

from typing import Dict, Any, Optional
from src.analytics.schedule_matrix import TEAM_ALIASES

TEAM_SCHEME_INTEL: Dict[str, Dict[str, Any]] = {
    "SF": {
        "tree_label": "👑 Kyle Shanahan Wide Zone (Gold Standard)",
        "mentor_tree": "Shanahan Tree Archetype",
        "is_shanahan_tree": True,
        "is_top_eco": True,
        "primary_tendency": "Heavy Pre-Snap Motion • Elite YAC Creation • 68% GL Run Funnel",
        "playcaller": "Kyle Shanahan",
        "motion_rank": 2,
        "proe_tag": "Balanced Efficiency (-1.9%)",
        "personnel_tag": "Condensed 21/11p",
    },
    "LAR": {
        "tree_label": "👑 McVay 11-Personnel Tree (Gold Standard)",
        "mentor_tree": "McVay Tree Archetype",
        "is_shanahan_tree": True,
        "is_top_eco": True,
        "primary_tendency": "Top-3 Motion • Elite Target Consolidation (Puka/Kupp) • 11-Personnel",
        "playcaller": "Sean McVay",
        "motion_rank": 3,
        "proe_tag": "Balanced Pass (+0.3%)",
        "personnel_tag": "88% 11 Personnel (3-WR)",
    },
    "MIA": {
        "tree_label": "👑 Shanahan/McDaniel Speed Tree",
        "mentor_tree": "Shanahan Tree",
        "is_shanahan_tree": True,
        "is_top_eco": True,
        "primary_tendency": "Fastest Motion in NFL (#1) • Perimeter Speed Zone • Play-Action",
        "playcaller": "Bobby Slowik / Mike McDaniel",
        "motion_rank": 1,
        "proe_tag": "Balanced Pass (+0.3%)",
        "personnel_tag": "21/11 Personnel",
    },
    "DET": {
        "tree_label": "⭐ Top-10 Eco: High-Motion Zone/PA (Ben Johnson/Campbell)",
        "mentor_tree": "Shanahan/Campbell Lineage",
        "is_shanahan_tree": True,
        "is_top_eco": True,
        "primary_tendency": "Top-3 Scoring Eco • 74% GL Run Funnel (Gibbs Bellcow) • Elite Play-Action",
        "playcaller": "Ben Johnson",
        "motion_rank": 4,
        "proe_tag": "Balanced Ground (-1.1%)",
        "personnel_tag": "12/21 Personnel",
    },
    "KC": {
        "tree_label": "🚀 Andy Reid Pass-Heavy Spread (Elite Pass Eco)",
        "mentor_tree": "Reid / Holmgren Tree",
        "is_shanahan_tree": False,
        "is_top_eco": True,
        "primary_tendency": "Top-5 Pass PROE (+6.4%) • Pre-Snap Motion & Screen Master • RZ Pass Funnel",
        "playcaller": "Andy Reid",
        "motion_rank": 5,
        "proe_tag": "Extreme Pass-Heavy (+6.4%)",
        "personnel_tag": "11/12 Personnel Spread",
    },
    "ATL": {
        "tree_label": "👑 Shanahan/Stefanski Wide Zone Lineage",
        "mentor_tree": "Shanahan Tree",
        "is_shanahan_tree": True,
        "is_top_eco": False,
        "primary_tendency": "Heavy Motion • 3-Down Workhorse Funnel (Bijan) • 70% GL Run",
        "playcaller": "Kevin Stefanski / Zac Robinson",
        "motion_rank": 6,
        "proe_tag": "Ground-Heavy Zone (-4.2%)",
        "personnel_tag": "11/12 Personnel",
    },
    "CIN": {
        "tree_label": "🎯 Zac Taylor 11-Spread (McVay Tree)",
        "mentor_tree": "McVay Tree",
        "is_shanahan_tree": True,
        "is_top_eco": True,
        "primary_tendency": "Pass-Heavy (+3.6% PROE) • Empty Backfield Sets • 65% RZ Pass Funnel",
        "playcaller": "Zac Taylor",
        "motion_rank": 14,
        "proe_tag": "Pass-Heavy (+3.6%)",
        "personnel_tag": "85% 11 Personnel (3-WR)",
    },
    "IND": {
        "tree_label": "⚡ Steichen Fast-Pace Zone-Read (RPO)",
        "mentor_tree": "Steichen / Sirianni Lineage",
        "is_shanahan_tree": False,
        "is_top_eco": False,
        "primary_tendency": "Top-5 Neutral Pace • 69% GL Run Funnel (JT) • Mobile QB Option",
        "playcaller": "Shane Steichen",
        "motion_rank": 18,
        "proe_tag": "Run-Leaning RPO (-3.5%)",
        "personnel_tag": "11 Personnel",
    },
    "PHI": {
        "tree_label": "👑 Top-5 Eco: Power RPO / Tush Push (Mannion/Moore)",
        "mentor_tree": "Sirianni / Moore Lineage",
        "is_shanahan_tree": False,
        "is_top_eco": True,
        "primary_tendency": "78% GL Run Funnel (Saquon/Hurts) • Top-5 OL • Condensed 2-WR Sets",
        "playcaller": "Sean Mannion / Kellen Moore",
        "motion_rank": 12,
        "proe_tag": "Balanced Ground (0.0%)",
        "personnel_tag": "11/12 Personnel",
    },
    "BAL": {
        "tree_label": "⚡ Monken Power-Pistol Spread",
        "mentor_tree": "Monken / Roman Lineage",
        "is_shanahan_tree": False,
        "is_top_eco": True,
        "primary_tendency": "72% GL Run Funnel (Henry/Lamar) • Pre-Snap Motion • Lamar Read-Option",
        "playcaller": "Todd Monken",
        "motion_rank": 7,
        "proe_tag": "Ground-Heavy Option (0.0%)",
        "personnel_tag": "12/21 Personnel Pistol",
    },
    "GB": {
        "tree_label": "👑 LaFleur Shanahan/McVay Tree",
        "mentor_tree": "Shanahan/McVay Tree",
        "is_shanahan_tree": True,
        "is_top_eco": True,
        "primary_tendency": "Heavy Motion • Play-Action Deep Shots • 67% GL Run Funnel (Jacobs)",
        "playcaller": "Matt LaFleur",
        "motion_rank": 8,
        "proe_tag": "Balanced Zone (-1.0%)",
        "personnel_tag": "11/12 Personnel",
    },
    "CHI": {
        "tree_label": "🔥 Ben Johnson Creative Motion (Top Eco)",
        "mentor_tree": "Campbell / Shanahan Lineage",
        "is_shanahan_tree": True,
        "is_top_eco": False,
        "primary_tendency": "Elite Motion • Creative 11/12P RPO • RZ Spread Funnel (Odunze/Burden/Loveland)",
        "playcaller": "Ben Johnson",
        "motion_rank": 5,
        "proe_tag": "Balanced Spread (-2.7%)",
        "personnel_tag": "11/12 Personnel",
    },
    "MIN": {
        "tree_label": "🎯 O'Connell McVay Pass Funnel (Top PROE)",
        "mentor_tree": "McVay Tree",
        "is_shanahan_tree": True,
        "is_top_eco": False,
        "primary_tendency": "Pass-Forward System (+1.4% PROE) • 11-Personnel • Alpha Target Consolidation (Jefferson)",
        "playcaller": "Kevin O'Connell",
        "motion_rank": 10,
        "proe_tag": "Pass-Leaning (+1.4%)",
        "personnel_tag": "86% 11 Personnel (3-WR)",
    },
    "BUF": {
        "tree_label": "⭐ Top-10 Eco: Power Spread (Joe Brady)",
        "mentor_tree": "Brady / Payton Lineage",
        "is_shanahan_tree": False,
        "is_top_eco": True,
        "primary_tendency": "Multi-TE 12p Power • Josh Allen Scramble Floor • DJ Moore / Kincaid Target Funnel",
        "playcaller": "Joe Brady",
        "motion_rank": 16,
        "proe_tag": "Balanced Ground (-1.6%)",
        "personnel_tag": "12 Personnel Heavy (Kincaid/Knox)",
    },
    "HOU": {
        "tree_label": "👑 Shanahan Wide Zone Tree (Slowik/Johnson)",
        "mentor_tree": "Shanahan Tree",
        "is_shanahan_tree": True,
        "is_top_eco": True,
        "primary_tendency": "Top-10 Eco • Outside Zone • Play-Action Deep Shots (Stroud/Collins)",
        "playcaller": "Jerrod Johnson / Bobby Slowik",
        "motion_rank": 9,
        "proe_tag": "Balanced Zone (-0.5%)",
        "personnel_tag": "11 Personnel Spread",
    },
    "TB": {
        "tree_label": "🎯 Liam Coen McVay Spread (Pass Funnel)",
        "mentor_tree": "McVay Tree",
        "is_shanahan_tree": True,
        "is_top_eco": False,
        "primary_tendency": "11-Personnel Spread • Play-Action Deep Funnel (Evans/Godwin) • Workhorse Ground Flow",
        "playcaller": "Liam Coen",
        "motion_rank": 11,
        "proe_tag": "Ground-Leaning Play-Action (-6.6%)",
        "personnel_tag": "84% 11 Personnel",
    },
    "WAS": {
        "tree_label": "⚡ Kingsbury Air Raid (Top-3 Pace)",
        "mentor_tree": "Air Raid Lineage",
        "is_shanahan_tree": False,
        "is_top_eco": False,
        "primary_tendency": "Top-3 Neutral Pace • Read-Option Spread • Dual-Threat Floor (Daniels)",
        "playcaller": "Kliff Kingsbury",
        "motion_rank": 15,
        "proe_tag": "Fast-Pace Balanced (0.0%)",
        "personnel_tag": "11 Personnel Quick Tempo",
    },
    "DEN": {
        "tree_label": "🎯 Sean Payton West Coast Spread",
        "mentor_tree": "Payton / Parcells Lineage",
        "is_shanahan_tree": False,
        "is_top_eco": False,
        "primary_tendency": "High RB Target Share • Screen Heavy • Quick-Timing RZ Funnel",
        "playcaller": "Sean Payton",
        "motion_rank": 17,
        "proe_tag": "Pass-Leaning (+1.7%)",
        "personnel_tag": "11/12 Personnel",
    },
    "SEA": {
        "tree_label": "🎯 Fleury/Grubb Deep Spread (2-WR Funnel)",
        "mentor_tree": "Grubb / DeBoer Lineage",
        "is_shanahan_tree": False,
        "is_top_eco": False,
        "primary_tendency": "47% 2-WR Target Funnel (JSN/DK) • Downfield Air Yards • Play-Action Flow",
        "playcaller": "Brian Fleury / Ryan Grubb",
        "motion_rank": 13,
        "proe_tag": "Balanced Spread (0.0%)",
        "personnel_tag": "Condensed 2-WR Focus",
    },
    "PIT": {
        "tree_label": "🏃 Arthur Smith Heavy Zone Lineage",
        "mentor_tree": "Shanahan / Titans Lineage",
        "is_shanahan_tree": True,
        "is_top_eco": False,
        "primary_tendency": "Heavy 12/13 Personnel (Multiple TEs) • +4.6% PROE • Outside Zone & PA Shots",
        "playcaller": "Arthur Smith",
        "motion_rank": 20,
        "proe_tag": "Pass-Forward Lineage (+4.6%)",
        "personnel_tag": "12/13 Personnel Heavy",
    },
    "LAC": {
        "tree_label": "👑 McDaniel/Harbaugh Power Zone Lineage",
        "mentor_tree": "Shanahan / Harbaugh Lineage",
        "is_shanahan_tree": True,
        "is_top_eco": False,
        "primary_tendency": "Power Outside Zone • 71% GL Run Funnel (Hampton) • Heavy Play-Action",
        "playcaller": "Mike McDaniel / Jim Harbaugh",
        "motion_rank": 19,
        "proe_tag": "Ground-Leaning (-1.4%)",
        "personnel_tag": "12/21 Personnel Heavy",
    },
    "LV": {
        "tree_label": "👑 Klint Kubiak Shanahan Tree",
        "mentor_tree": "Shanahan Tree",
        "is_shanahan_tree": True,
        "is_top_eco": False,
        "primary_tendency": "Shanahan Pre-Snap Motion • Condensed Splits • Target Consolidation (Adams/Bowers)",
        "playcaller": "Klint Kubiak",
        "motion_rank": 10,
        "proe_tag": "Ground-Leaning Zone (-4.3%)",
        "personnel_tag": "11/12 Personnel",
    },
    "NO": {
        "tree_label": "👑 Klint Kubiak Shanahan Motion Tree",
        "mentor_tree": "Shanahan Tree",
        "is_shanahan_tree": True,
        "is_top_eco": False,
        "primary_tendency": "Pre-Snap Motion • Condensed Formation • Kamara/Olave Target Funnel",
        "playcaller": "Klint Kubiak",
        "motion_rank": 8,
        "proe_tag": "Balanced Motion (-2.3%)",
        "personnel_tag": "11/12 Personnel",
    },
    "JAX": {
        "tree_label": "🎯 Doug Pederson West Coast RPO",
        "mentor_tree": "Reid / Pederson Lineage",
        "is_shanahan_tree": False,
        "is_top_eco": False,
        "primary_tendency": "High Pass Volume • RPO Spacing • Pass-Heavy RZ (Engram/Lawrence)",
        "playcaller": "Doug Pederson / Press Taylor",
        "motion_rank": 21,
        "proe_tag": "Pass-Leaning (+0.9%)",
        "personnel_tag": "11 Personnel Spread",
    },
    "ARI": {
        "tree_label": "👑 Petzing Shanahan/Stefanski Tree",
        "mentor_tree": "Shanahan Tree",
        "is_shanahan_tree": True,
        "is_top_eco": False,
        "primary_tendency": "Outside Zone • Multi-TE Target Funnel (McBride) • Kyler Scrambles",
        "playcaller": "Drew Petzing",
        "motion_rank": 12,
        "proe_tag": "Balanced Zone (-1.1%)",
        "personnel_tag": "12 Personnel Heavy",
    },
    "DAL": {
        "tree_label": "⚡ Schottenheimer West Coast Spread (Top Pace)",
        "mentor_tree": "McCarthy / Schottenheimer Lineage",
        "is_shanahan_tree": False,
        "is_top_eco": True,
        "primary_tendency": "Top-3 Neutral Pace • 61% RZ Pass Funnel (Dak/Lamb) • High Overall Tempo",
        "playcaller": "Brian Schottenheimer",
        "motion_rank": 22,
        "proe_tag": "Balanced Ground (-3.4%)",
        "personnel_tag": "11 Personnel",
    },
    "CAR": {
        "tree_label": "⚡ Canales McVay/Waldron Quick Game",
        "mentor_tree": "McVay / Carroll Lineage",
        "is_shanahan_tree": True,
        "is_top_eco": False,
        "primary_tendency": "Fast-Pace 11-Personnel • Quick Timing Pass • Steady RB Floor",
        "playcaller": "Dave Canales",
        "motion_rank": 16,
        "proe_tag": "Balanced Quick Game (-2.0%)",
        "personnel_tag": "11 Personnel",
    },
    "CLE": {
        "tree_label": "🎯 Ken Dorsey Air Raid Spread",
        "mentor_tree": "Air Raid / Dorsey Lineage",
        "is_shanahan_tree": False,
        "is_top_eco": False,
        "primary_tendency": "Shotgun Pass Spacing • Downfield Air Yards • Deep Ball Frequency",
        "playcaller": "Ken Dorsey",
        "motion_rank": 24,
        "proe_tag": "Balanced Ground (-3.2%)",
        "personnel_tag": "11/10 Personnel Spread",
    },
    "TEN": {
        "tree_label": "🎯 Callahan McVay/Taylor Spread",
        "mentor_tree": "McVay / Taylor Lineage",
        "is_shanahan_tree": True,
        "is_top_eco": False,
        "primary_tendency": "Pass-Heavy 11-Spread • 3-WR Focus • Shotgun Pass Funnel",
        "playcaller": "Brian Callahan",
        "motion_rank": 23,
        "proe_tag": "Balanced Spread (-1.4%)",
        "personnel_tag": "11 Personnel",
    },
    "NYJ": {
        "tree_label": "🎯 Engstrand West Coast Spread",
        "mentor_tree": "West Coast Lineage",
        "is_shanahan_tree": False,
        "is_top_eco": False,
        "primary_tendency": "11-Personnel • Quick Timing • Alpha Target Consolidation (Wilson/Hall)",
        "playcaller": "Tanner Engstrand",
        "motion_rank": 25,
        "proe_tag": "Balanced Spread (-1.3%)",
        "personnel_tag": "11 Personnel",
    },
    "NYG": {
        "tree_label": "⚡ Daboll Spread Option",
        "mentor_tree": "Daboll / Belichick Lineage",
        "is_shanahan_tree": False,
        "is_top_eco": False,
        "primary_tendency": "Read-Option • High Tempo Floor • Quick Perimeter Spacing (Nabers Alpha)",
        "playcaller": "Brian Daboll",
        "motion_rank": 26,
        "proe_tag": "Pass-Leaning (+1.3%)",
        "personnel_tag": "11 Personnel",
    },
    "NE": {
        "tree_label": "🏃 Van Pelt Power West Coast",
        "mentor_tree": "Stefanski / Van Pelt Lineage",
        "is_shanahan_tree": True,
        "is_top_eco": False,
        "primary_tendency": "Heavy 12/21 Personnel • Under-Center Ground • Rhamondre Volume Floor",
        "playcaller": "Alex Van Pelt",
        "motion_rank": 27,
        "proe_tag": "Pass-Leaning (+1.4%)",
        "personnel_tag": "12/21 Personnel Heavy",
    }
}


class SchemeEcosystemEngine:
    """Provides high-signal scheme architecture and coaching lineage intelligence."""

    @staticmethod
    def get_scheme_intel(team: str) -> Dict[str, Any]:
        raw_tm = str(team).strip().upper()
        tm = TEAM_ALIASES.get(raw_tm, raw_tm)
        return TEAM_SCHEME_INTEL.get(tm, {
            "tree_label": f"Scheme: {tm}",
            "mentor_tree": "Standard NFL Scheme",
            "is_shanahan_tree": False,
            "is_top_eco": False,
            "primary_tendency": "Standard Personnel & Neutral Pace",
            "playcaller": "—",
            "motion_rank": 16,
            "proe_tag": "Neutral",
            "personnel_tag": "11 Personnel"
        })
